export const userTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER'
};

export const cartTypes = {
  TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_CART_ITEM: 'CLEAR_CART_ITEM'
};

export const shopTypes = {
  UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS'
};
